### ISSUE TITLE
VOLTTRON Central Agent Showing status of 1

### ISSUE THREAD

**Issue by judymin88** [VOLTTRON/volttron-docker#48]
I uncommented the VOLTTRON Central Agent code in the platform_config.yml file and when I run vctl status I am getting a status of 1. Searching through the logs I found the following error:

2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: Traceback (most recent call last):
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: "__main__", mod_spec)
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: exec(code, run_globals)
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: File "/home/volttron/.volttron/agents/eee54433-f080-45c4-bfc5-5d64993fdba1/volttroncentralagent-5.2/volttroncentral/agent.py", line 1022, in <module>
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: sys.exit(main())
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: File "/home/volttron/.volttron/agents/eee54433-f080-45c4-bfc5-5d64993fdba1/volttroncentralagent-5.2/volttroncentral/agent.py", line 1016, in main
2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) <stderr> ERROR: version=__version__)
2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) <stderr> ERROR: File "/code/volttron/volttron/platform/agent/utils.py", line 459, in vip_main
2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) <stderr> ERROR: message_bus=message_bus, **kwargs)
2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) <stderr> ERROR: File "/home/volttron/.volttron/agents/eee54433-f080-45c4-bfc5-5d64993fdba1/volttroncentralagent-5.2/volttroncentral/agent.py", line 109, in init_volttron_central
2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) <stderr> ERROR: users = config.get('users', None)
2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) <stderr> ERROR: AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bonicim** [comment]
The agent configuration for this Volttron Central Agent is an yaml file that has no yaml objects, not even an empty object. Because the config file is empty, the Volttron platform is returning a NoneType for the 'config' object, thus failing this installation when the agent code is trying to get a property on a None object. To resolve this, ensure that the Volttron Agent config file has at least an empty dictionary.

**Comment by bonicim** [comment]
> I uncommented the VOLTTRON Central Agent code in the platform_config.yml file and when I run vctl status I am getting a status of 1. Searching through the logs I found the following error:
> 
> 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: Traceback (most recent call last): 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: "**main**", mod_spec) 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: File "/usr/lib/python3.7/runpy.py", line 85, in _run_code 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: exec(code, run_globals) 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: File "/home/volttron/.volttron/agents/eee54433-f080-45c4-bfc5-5d64993fdba1/volttroncentralagent-5.2/volttroncentral/agent.py", line 1022, in 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: sys.exit(main()) 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: File "/home/volttron/.volttron/agents/eee54433-f080-45c4-bfc5-5d64993fdba1/volttroncentralagent-5.2/volttroncentral/agent.py", line 1016, in main 2021-11-22 17:22:16,828 (volttroncentralagent-5.2 177) ERROR: version=**version**) 2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) ERROR: File "/code/volttron/volttron/platform/agent/utils.py", line 459, in vip_main 2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) ERROR: message_bus=message_bus, **kwargs) 2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) ERROR: File "/home/volttron/.volttron/agents/eee54433-f080-45c4-bfc5-5d64993fdba1/volttroncentralagent-5.2/volttroncentral/agent.py", line 109, in init_volttron_central 2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) ERROR: users = config.get('users', None) 2021-11-22 17:22:16,829 (volttroncentralagent-5.2 177) ERROR: AttributeError: 'NoneType' object has no attribute 'get'

@judymin88 Try adding your own Volttron config file and using it for the agent config for Volttron Central Agent. See my solution in #51
