### ISSUE TITLE
Unable to access VOLTTRON central

### ISSUE THREAD

**Issue by DougPlumley** [VOLTTRON/volttron-docker#66]
Hi,

I'm attempting to make use of the quick start which seems like it should be fairly simple.

I pulled a copy of this repository and ran

```shell
docker-compose up
```

The container comes up and appears to initialize itself, I do see some errors but none seem to be terminating errors.  When I attempt to connect to 8443 on my local machine I'm unable to access anything via the browser.  I'm completely new to VOLTTRON so I apologize if I've missed something obvious.

My machine, I am forcing containers to run as AMD64 even though this is ARM64.

```
Software:

    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB

docker-compose --version
Docker Compose version v2.2.3

docker --version
Docker version 20.10.9, build c2ea9bc
```

Below is a sample of some of the errors I saw in the logs

```
volttron1  | 2022-07-22 16:40:21,214 () volttron.platform.agent.utils INFO: Adding file watch for /home/volttron/.volttron/auth.json dirname=/home/volttron/.volttron, filename=auth.json
volttron1  | Traceback (most recent call last):
volttron1  |   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
volttron1  |   File "/code/volttron/volttron/platform/agent/utils.py", line 703, in watch_file
volttron1  |     observer.start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/api.py", line 256, in start
volttron1  |     emitter.start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 93, in start
volttron1  |     self.on_thread_start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
volttron1  |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
volttron1  |     self._inotify = Inotify(path, recursive)
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 155, in __init__
volttron1  |     Inotify._raise_error()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
volttron1  |     raise OSError(err, os.strerror(err))
volttron1  | OSError: [Errno 38] Function not implemented
volttron1  | 2022-07-22T16:40:21Z <Greenlet at 0x400a1efd08: watch_file('/home/volttron/.volttron/auth.json', <bound method AuthService.read_auth_file of <voltt)> failed with OSError
volttron1  | 
volttron1  | 2022-07-22 16:40:21,242 () volttron.platform.agent.utils INFO: Adding file watch for /home/volttron/.volttron/protected_topics.json dirname=/home/volttron/.volttron, filename=protected_topics.json
volttron1  | Traceback (most recent call last):
volttron1  |   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
volttron1  |   File "/code/volttron/volttron/platform/agent/utils.py", line 703, in watch_file
volttron1  |     observer.start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/api.py", line 256, in start
volttron1  |     emitter.start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 93, in start
volttron1  |     self.on_thread_start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
volttron1  |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
volttron1  |     self._inotify = Inotify(path, recursive)
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 155, in __init__
volttron1  |     Inotify._raise_error()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
volttron1  |     raise OSError(err, os.strerror(err))
volttron1  | OSError: [Errno 38] Function not implemented
volttron1  | 2022-07-22T16:40:21Z <Greenlet at 0x400a1efe18: watch_file('/home/volttron/.volttron/protected_topics.json', <bound method AuthService._read_protected_topics_f)> failed with OSError
volttron1  | 
volttron1  | 2022-07-22 16:40:21,264 () volttron.platform.vip.pubsubservice INFO: protected-topics loaded
```

```
volttron1  | Available agents that are needing to be setup/installeddict_keys(['listener', 'platform.driver', 'platform.agent', 'platform.actuator', 'platform.historian', 'volttron.central'])
volttron1  | 2022-07-22 16:40:35 INFO setup-platform install_agents:246 — Processing identity: listener
volttron1  | Traceback (most recent call last):
volttron1  |   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
volttron1  |   File "/code/volttron/volttron/platform/web/platform_web_service.py", line 776, in startupagent
volttron1  |     rpc_caller=rpc_caller)
volttron1  |   File "/code/volttron/volttron/platform/web/admin_endpoints.py", line 110, in __init__
volttron1  |     self._observer.start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/api.py", line 256, in start
volttron1  |     emitter.start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 93, in start
volttron1  |     self.on_thread_start()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
volttron1  |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
volttron1  |     self._inotify = Inotify(path, recursive)
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 155, in __init__
volttron1  |     Inotify._raise_error()
volttron1  |   File "/home/volttron/.local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
volttron1  |     raise OSError(err, os.strerror(err))
volttron1  | OSError: [Errno 38] Function not implemented
volttron1  | 2022-07-22T16:40:24Z <Greenlet at 0x4024439bf8: <bound method PlatformWebService.startupagent of <volttron.platform.web.platform_web_service.PlatformWebService object at 0x400a31b438>>(<volttron.platform.vip.agent.core.ZMQCore object a)> failed with OSError
```

```
volttron1  | Processing identity: listener
volttron1  | 2022-07-22 16:40:53 INFO setup-platform install_agents:246 — Processing identity: platform.driver
volttron1  | 2022-07-22 16:40:55,508 (listeneragent-3.3 165) volttron.platform.vip.agent.core ERROR: No response to hello message after 10 seconds.
volttron1  | 2022-07-22 16:40:55,508 (listeneragent-3.3 165) volttron.platform.vip.agent.core ERROR: Type of message bus used zmq
volttron1  | 2022-07-22 16:40:55,508 (listeneragent-3.3 165) volttron.platform.vip.agent.core ERROR: A common reason for this is a conflicting VIP IDENTITY.
volttron1  | 2022-07-22 16:40:55,509 (listeneragent-3.3 165) volttron.platform.vip.agent.core ERROR: Another common reason is not having an auth entry onthe target instance.
volttron1  | 2022-07-22 16:40:55,509 (listeneragent-3.3 165) volttron.platform.vip.agent.core ERROR: Shutting down agent.
volttron1  | 2022-07-22 16:40:55,509 (listeneragent-3.3 165) volttron.platform.vip.agent.core ERROR: Possible conflicting identity is: listener
```

**Comment by DougPlumley** [comment]
I'll add that based on the logs it looks like VOLTTRON is unable to connect on 8443 within the container as well.

```
volttron1  | 2022-07-22 16:45:37,852 (vcplatformagent-4.8 467) volttron.platform.vip.agent.subsystems.auth DEBUG: Begining auth.connect_remote_platform: https://0.0.0.0:8443
volttron1  | 2022-07-22 16:45:37,855 (vcplatformagent-4.8 467) volttron.platform.web.discovery INFO: Connecting to: https://0.0.0.0:8443/discovery/
volttron1  | 2022-07-22 16:45:37,880 (vcplatformagent-4.8 467) volttron.platform.vip.agent.subsystems.auth ERROR: Couldn't connect to https://0.0.0.0:8443 or incorrect response returned response was None
volttron1  | 2022-07-22 16:45:37,882 (vcplatformagent-4.8 467) <stderr> ERROR: ERROR:volttron.platform.vip.agent.subsystems.auth:Couldn't connect to https://0.0.0.0:8443 or incorrect response returned response was None
```

**Comment by craigpnnl** [comment]
The error with inotify is indicative of it running on mac natively.  Did you build the container or is it one that we have on dockerhub?

**Comment by DougPlumley** [comment]
> The error with inotify is indicative of it running on mac natively. Did you build the container or is it one that we have on dockerhub?

I didn't specifically build it locally (that I'm aware of), I believe it's the image from dockerhub.  I basically pulled this repository as is and ran docker-compose up

**Comment by DougPlumley** [comment]
@craig8 I did some more research and it looks like Apple M1 running Docker desktop and underneath the covers qemu for the Linux VM may not support file system notifications.

https://github.com/docker/for-mac/issues/6174

https://github.com/docker/for-mac/issues/6174#issuecomment-1048928733

**Comment by DougPlumley** [comment]
And specifically this appears to be an issue with the emulation of amd64 on the arm64 Apple M1 silicon.  I had been forcing my entire system to utilize amd64 images due to the nature of the binaries I was working with and to stay mostly compatible with my team on some of my other projects.

I think this is an issue for me to workaround.  Appreciate the time you took to look at this, thank you!

**Comment by craigpnnl** [comment]
@DougPlumley cheers
